title: LiGaoPeng'Log
name: "LiGaoPeng's Tech Blog"
author: Ligaopeng
twitter_username: ligaopeng
baseurl: "/lil-log"
description: Document my learning notes.
profile_url: "https://ligaopengde.github.io/"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..4
